import "@fontsource/instrument-serif/400.css";
import "@fontsource/inter/400.css";
import "@fontsource/inter/500.css";
import "@fontsource/ibm-plex-mono/400.css";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "@nexova/design-system/theme.css";
import "./styles.css";
import { App } from "./App";
const root=document.getElementById("root"); if(!root) throw new Error("Website root element was not found.");
createRoot(root).render(<StrictMode><App/></StrictMode>);
